### ISSUE TITLE
新增模版并没有显示

### ISSUE THREAD

**Issue by cxyxiaokui** [zjh7890/gpt-tools#29]
![image](https://github.com/user-attachments/assets/64f4da67-38f4-4427-bf73-b54148d0aa66)
![image](https://github.com/user-attachments/assets/ee244314-c1e8-4c62-909f-d6af21a44c60)
去掉 * 号也不行

**Comment by cxyxiaokui** [comment]
这个模板是只能修改原来的吗？ 还有一个 add to Session File List 点击也不会打开 chat 窗口

**Comment by zjh7890** [comment]
我试了下可以呀，你是点 + 号新增的吗？
* 是内置模板，改了也不生效的。
add to Session File List  这个后面会优化交互，不过文件应该已经加进列表了吧

**Comment by zjh7890** [comment]
*是内置模板，改了也不生效的。

**Comment by zjh7890** [comment]
模板现在的变量有点乱，后面会规范一波。

**Comment by cxyxiaokui** [comment]
我是新增的模板没有出来

**Comment by cxyxiaokui** [comment]
> 我试了下可以呀，你是点 + 号新增的吗？
> 
> * 是内置模板，改了也不生效的。
>   add to Session File List  这个后面会优化交互，不过文件应该已经加进列表了吧
是的 我是通过加号是我的 IDEA 版本的问题吗？ 我版本是：2024.2
<img width="677" alt="image" src="https://github.com/user-attachments/assets/59e69f55-b44d-4f54-951f-c621fa0c20d6">

<img width="539" alt="image" src="https://github.com/user-attachments/assets/8cf42d0c-c623-4125-84d8-e83a3b72e295">

**Comment by zjh7890** [comment]
Key 不对。
Key 只支持现在有的那些，Key 对应着一组内置变量，变量里面包含了一些上下文。

**Comment by cxyxiaokui** [comment]
嗯嗯 我看是可以了， 非常感谢！
