### ISSUE TITLE
diff 生成的新文件点击 Accept 并没有新增文件 如果有文件也不会插入到文件中

### ISSUE THREAD

**Issue by cxyxiaokui** [zjh7890/gpt-tools#30]
![image](https://github.com/user-attachments/assets/c5973e07-5110-4578-af33-0f1c113dd2ef)

**Comment by cxyxiaokui** [comment]
希望可以新增复制的按钮可以进行快捷复制

**Comment by zjh7890** [comment]
可以，目前可以全选后复制 Ctrl A + Ctrl C

cxyxiaokui ***@***.***>于2024年11月19日 周二下午8:07写道：

**Comment by zjh7890** [comment]
你加我微信吧，插件刚开始有人用问题是有点多，不用麻烦来这提 bug 了😂
![1971732022918_ pic](https://github.com/user-attachments/assets/58815de9-a14f-4f43-a277-95314e8ff1a2)

**Comment by cxyxiaokui** [comment]
ok 已添加
